DELETE http://localhost:8080/events/4
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAZXhhbXBsZS5jb20iLCJleHAiOjE3MzMxNTYzMDEsInVzZXJJZCI6MX0.MbSAmNQOGTTEbe_jFjVx6VllxV9v3HJdWMmrSdxkHm0